### ISSUE TITLE
go.work in root

### ISSUE THREAD

**Issue by gedw99** [maddalax/htmgo#38]
add a go.work to make vscode  / delve happy when working with the sub projects.

**Comment by maddalax** [comment]
I actually have a go.work that I used but the advice I saw was to not check it into git, not quite sure why that is since this seems helpful enough. This thread has some opinions: https://github.com/golang/go/issues/53502

I checked it in for now because I don't see a reason to not, thanks for suggesting

**Comment by maddalax** [comment]
I think it will break CI if I check it in because one of the workflows runs `htmgo template` to ensure it still works. I'll paste my go.work file here if you want to use it locally for now:

```
go 1.23.0

use (
	cli/htmgo
	examples/todo-list
	framework
	framework-ui
	htmgo-site
	templates/starter
	examples/chat
	examples/hackernews
	tools/html-to-htmgo
	examples/simple-auth
)

```

There also doesn't seem to be consensus on if go.mod should be checked: https://github.com/golang/go/issues/53502
